checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"
tasks:
  - before: |
      cat <<EOT >> ~/.bashrc.d/99-environment
      export PYTHONPATH=../../../
      export ANSIBLE_COLLECTIONS_PATHS=/workspace/ansible_collections
      EOT
  - init: |
      pip3 install -r requirements.txt
      pip3 install pre-commit

      . ~/.bashrc.d/99-environment

      scripts/ensure-venv.sh
      . .venv/bin/activate

      pip install pre-commit
      ansible-galaxy collection install --upgrade ansible.netcommon ansible.utils -p "./../../"

vscode:
  extensions:
    - ms-python.python
