checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"
tasks:
  - before: |
      eval $(gp env -e PYTHONPATH=../../../)
      export ANSIBLE_COLLECTIONS_PATH2=/workspace/ansible_collections
  - init: |
      pip3 install -r requirements.txt
      pip3 install pre-commit

      export ANSIBLE_COLLECTIONS_PATH=/workspace/ansible_collections
      ansible-galaxy collection install --upgrade ansible.netcommon -p "./../../"

vscode:
  extensions:
    - ms-python.python
