image:
  file: .gitpod.Dockerfile

checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"

tasks:
  - before: |
      direnv allow zyxel_vmg8825

      echo 'eval "$(direnv hook bash)"' > $HOME/.bashrc.d/300-direnv.bashrc

  - init: |
      direnv allow
      direnv exec . python3 -m pip install --upgrade pip
      direnv exec . python3 -m pip install pre-commit

      direnv exec . pre-commit

vscode:
  extensions:
    - ms-python.python
