image:
  file: .gitpod.Dockerfile

checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"

tasks:
  - before: |
      cd ..
      direnv allow zyxel_vmg8825
  - init: |
      python3 -m pip install --upgrade pip
      pip install pre-commit

vscode:
  extensions:
    - ms-python.python
