checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"
tasks:
  - before: |
      gp env -e PYTHONPATH=../../../:$PYTHONPATH
  - init: |
      pip3 install -r requirements.txt
      pip3 install pre-commit
      ansible-galaxy collection install --upgrade ansible.netcommon -p "./../../"

vscode:
  extensions:
    - ms-python.python
