image:
  file: .gitpod.Dockerfile

checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"

tasks:
  - before: |
      cd ..
      direnv allow zyxel_vmg8825

  - init: |
      direnv allow
      
      bash -c 'direnv exec . python3 -m pip install --upgrade pip'
      bash -c 'direnv exec . python3 -m pip install pre-commit'

      bash -c 'direnv exec . pre-commit'

vscode:
  extensions:
    - ms-python.python
