image:
  file: .gitpod.Dockerfile

checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"

tasks:
  - init: |
      cd ..

      direnv allow zyxel_vmg8825
      
      direnv exec zyxel_vmg8825 python3 -m pip install --upgrade pip
      direnv exec zyxel_vmg8825 python3 -m pip install pre-commit

      direnv exec zyxel_vmg8825 bash -c 'cd zyxel_vmg8825 && pre-commit'

      cd zyxel_vmg8825

      direnv allow
    env:
      PRE_COMMIT_HOME: /workspace/.cache/pre-commit

vscode:
  extensions:
    - ms-python.python
