checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"
tasks:
  - before: |
      cat <<EOT >> ~/.bashrc.d/99-environment
      export PYTHONPATH=../../../
      export ANSIBLE_COLLECTIONS_PATHS2=/workspace/ansible_collections
      EOT
  - init: |
      pip3 install -r requirements.txt
      pip3 install pre-commit

      #export ANSIBLE_COLLECTIONS_PATHS=/workspace/ansible_collections
      ansible-galaxy collection install --upgrade ansible.netcommon -p "./../../"

vscode:
  extensions:
    - ms-python.python
