image:
  file: .gitpod.Dockerfile

checkoutLocation: "ansible_collections/jwnmulder/zyxel_vmg8825"

tasks:
  - before: |
      echo 'eval "$(direnv hook bash)"' > $HOME/.bashrc.d/300-direnv.bashrc
      
      cd ..
      ls
      echo pre-direnv
      direnv allow zyxel_vmg8825
      echo post-direnv

  - init: |
      direnv allow
      python3 -m pip install --upgrade pip
      python3 -m pip install pre-commit

      pre-commit

vscode:
  extensions:
    - ms-python.python
