repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
        exclude: .devcontainer/|.vscode/
      - id: check-yaml
        files: .*\.(yaml|yml)$
        args:
          - --unsafe
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(plugins|tests)/.+\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args:
          - --extend-select=E,W,F
          - --ignore=E402,E501
        files: ^(plugins|tests)/.+\.py$
      # - id: ruff-format
      #   files: ^(plugins|tests)/.+\.py$

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.2
    hooks:
      - id: ansible-lint
        files: tests/integration/.*\.(yaml|yml)$
        args:
          - --force-color
          - -v
          - --warn-list=name[missing]
          - tests/integration
        always_run: false

  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.1
    hooks:
      - id: update-docs

  - repo: local
    hooks:
      - id: generate-changelog
        name: antsibull-changelog
        entry: antsibull-changelog generate
        language: python
        files: 'changelogs/.*'
        pass_filenames: false
        additional_dependencies:
          - antsibull-changelog==0.26.0  # renovate: datasource=pypi
