repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
        exclude: .devcontainer/|.vscode/
      - id: check-yaml
        files: .*\.(yaml|yml)$
        args:
          - --unsafe
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.15.0
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py38-plus]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.1
    hooks:
      - id: pycln
        args:
          - plugins
          - tests
          - --exclude
          - (\.eggs|\.git|\.hg|\.mypy_cache|__pycache__|\.nox|\.tox|\.venv|\.svn|buck-out|build|dist|output)/
        # TODO: When pycln resolves the issue
        # with click (to be precise, when the typer
        # dep fixes their issue with click), we should remove this
        additional_dependencies: ["click==8.0.4"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - --experimental-string-processing
        files: ^(plugins|tests)/.+\.py$
        # TODO: When pycln resolves the issue
        # with click (to be precise, when the typer
        # dep fixes their issue with click), we should remove this
        additional_dependencies: ["click==8.0.4"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          # https://github.com/DmytroLitvinov/awesome-flake8-extensions
          - pycodestyle==2.8.0  # renovate: datasource=pypi
          - pyflakes==2.4.0     # renovate: datasource=pypi
          # - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1   # renovate: datasource=pypi
          # - flake8-comprehensions==3.4.0
          - flake8-noqa==1.2.1  # renovate: datasource=pypi
        args:
          - --max-line-length=88
          - --ignore=E501,E402,W503
        files: ^(plugins|tests)/.+\.py$

  - repo: https://github.com/ansible-network/collection_prep
    rev: 0.9.6
    hooks:
      - id: update-docs
