repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
        exclude: .devcontainer/|.vscode/
      - id: check-yaml
        files: .*\.(yaml|yml)$
        args:
          - --unsafe
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.15.0
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py38-plus]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args:
          - plugins
          - tests
          - --exclude
          - (\.eggs|\.git|\.hg|\.mypy_cache|__pycache__|\.nox|\.tox|\.venv|\.svn|buck-out|build|dist|output)/

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(plugins|tests)/.+\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          # - flake8-docstrings
          - flake8-noqa
        args:
          - --max-line-length=88
          - --ignore=E501,E402,W503
        files: ^(plugins|tests)/.+\.py$

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        files: tests/integration/.*\.(yaml|yml)$
        args:
          - --force-color
          - -v
          - --warn-list=name[missing]
          - tests/integration
        always_run: false

  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.1
    hooks:
      - id: update-docs

  - repo: local
    hooks:
      - id: generate-changelog
        name: antsibull-changelog
        entry: antsibull-changelog generate
        language: python
        files: 'changelogs/.*'
        pass_filenames: false
        additional_dependencies:
          - antsibull-changelog==0.23.0  # renovate: datasource=pypi
