namespace: kokobana
name: zyxel_vmg8825
version: 0.2.0
readme: README.md
authors:
  - Jan-Willem Mulder (@jwnmulder)
description: 'A variety of Ansible modules to help automate the management of Zyxel VMG8825 routers'
license_file: LICENSE
tags:
  - zyxel
  - zyxel_vmg8825
dependencies:
  ansible.netcommon: '>=2.5.1'
repository: https://github.com/kokobana/ansible-collection-zyxel-vmg8825
documentation: https://github.com/kokobana/ansible-collection-zyxel-vmg8825/blob/main/README.md
homepage: https://github.com/kokobana/ansible-collection-zyxel-vmg8825
issues: https://github.com/kokobana/ansible-collection-zyxel-vmg8825/issues
build_ignore:
  - '.*'
  - '*.tar.gz'
  - 'changelogs/.plugin-cache.yaml'
  - 'rm_builder'
  - 'scripts'
  - 'renovate.json'
  - '**/inventory.networking'
