# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: jwnmulder
name: zyxel-vmg8825
version: 0.1.0
readme: README.md
authors:
  - Jan-Willem Mulder (@jwnmulder)
description: ""
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - zyxel
  - example2
dependencies:
  ansible.netcommon: '>=1.0.0'
repository: https://github.com/jwnmulder/ansible-collection-zyxel-vmg8825
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/jwnmulder/ansible-collection-zyxel-vmg8825
issues: https://github.com/jwnmulder/ansible-collection-zyxel-vmg8825
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
