# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: kokobana
name: zyxel_vmg8825
version: 0.2.0
readme: README.md
authors:
  - Jan-Willem Mulder (@jwnmulder)
description: ""
license_file: LICENSE
tags:
  - zyxel
  - zyxel_vmg8825
dependencies:
  ansible.netcommon: '>=2.5.1'
repository: https://github.com/kokobana/ansible-collection-zyxel-vmg8825
# documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/kokobana/ansible-collection-zyxel-vmg8825
issues: https://github.com/kokobana/ansible-collection-zyxel-vmg8825
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
