# -*- coding: utf-8 -*-
# Copyright 2022
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the zyxel_vmg8825_firewall_acls module
"""


class Firewall_aclsArgs(object):  # pylint: disable=R0903
    """The arg spec for the zyxel_vmg8825_firewall_acls module"""

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "index": {"type": "int"},
                "name": {"type": "str", "required": True},
                "order": {"type": "int"},
                "protocol": {
                    "type": "str",
                    "choices": ["ALL", "TCP", "UDP", "TCP_UDP", "ICMP"],
                    "default": "ALL",
                },
                "source_port": {"type": "int"},
                "source_port_range_max": {"type": "int"},
                "dest_port": {"type": "int"},
                "dest_port_range_max": {"type": "int"},
                "direction": {
                    "type": "str",
                    "choices": [
                        "WAN_TO_LAN",
                        "LAN_TO_WAN",
                        "WAN_TO_ROUTER",
                        "LAN_TO_ROUTER",
                    ],
                    "required": True,
                },
                "ip_version": {
                    "type": "str",
                    "choices": ["IPv4", "IPv6"],
                    "required": True,
                },
                "limit_rate": {"type": "int"},
                "limit_rate_unit": {
                    "type": "str",
                    "choices": ["minute", "second"],
                },
                "source_ip": {"type": "str", "required": True},
                "source_mask": {"type": "str", "default": "32"},
                "dest_ip": {"type": "str", "required": True},
                "dest_mask": {"type": "str", "default": "32"},
                "target": {
                    "type": "str",
                    "choices": ["Accept", "Drop", "Reject"],
                    "required": True,
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
