---
- hosts: localhost
  gather_facts: yes

  tasks:
    - include_vars: vars.yml
    - include_role:
        name: ansible_network.cli_rm_builder.run
      vars:
        collection_org: "jwnmulder"
        collection_name: "zyxel_vmg8825"
        network_os: "zyxel_vmg8825"
        transport: "httpapi"
        resource: "{{ i.resource }}"
      loop_control:
        loop_var: i
      loop:
        - { resource: 'static_dhcp_table' }
#        - { resource: 'interfaces' }
