# -*- coding: utf-8 -*-
# Copyright 2021
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the zyxel_vmg8825_nat_port_forwards module
"""


class Nat_port_forwardsArgs(object):  # pylint: disable=R0903
    """The arg spec for the zyxel_vmg8825_nat_port_forwards module"""

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "index": {"type": "int", "required": False},
                "enable": {"type": "bool", "default": True},
                "protocol": {
                    "type": "str",
                    "choices": ["TCP", "UDP", "ALL"],
                    "default": "TCP",
                },
                "description": {"type": "str", "required": True},
                "interface": {"type": "str", "required": True},
                "external_port_start": {"type": "int", "required": True},
                "external_port_end": {"type": "int", "required": True},
                "internal_port_start": {"type": "int", "required": True},
                "internal_port_end": {"type": "int", "required": True},
                "internal_client": {"type": "str", "required": True},
                "originating_ip_address": {"type": "str", "required": False},
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
