from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the zyxel_vmg8825_static_dhcp module
"""


class Static_dhcpArgs:  # pylint: disable=R0903
    """The arg spec for the zyxel_vmg8825_static_dhcp module"""

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "index": {"type": "int"},
                "enable": {"type": "bool", "default": True},
                "br_wan": {"type": "str", "default": "Default"},
                "mac_addr": {"type": "str", "required": True},
                "ip_addr": {"type": "str", "required": True},
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
