name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.3
